import argparse
from copy import deepcopy
from pathlib import Path

import yaml


def load_yaml(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def save_yaml(blob: dict, path: str) -> None:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        yaml.safe_dump(blob, f, sort_keys=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--primary", required=True, help="Primary config path.")
    ap.add_argument("--out", required=True, help="Output oracle config path.")
    ap.add_argument("--epochs-mult", type=float, default=1.0, help="Optional multiplier for rl.epochs.")
    ap.add_argument("--steps-mult", type=float, default=1.0, help="Optional multiplier for rl.steps_per_epoch.")
    args = ap.parse_args()

    cfg = load_yaml(args.primary)
    oracle = deepcopy(cfg)

    ood = deepcopy(cfg.get("eval", {}).get("ood", {}))
    if not ood:
        raise ValueError("Primary config missing eval.ood section.")
    ood.pop("seed_offset", None)

    oracle["env"] = deepcopy(ood)
    oracle.setdefault("eval", {})
    oracle["eval"]["id"] = deepcopy(ood)
    oracle["eval"]["ood"] = deepcopy(ood)
    oracle["eval"]["seed_offset"] = int(cfg.get("eval", {}).get("seed_offset", 123))
    oracle["eval"]["ood"]["seed_offset"] = int(cfg.get("eval", {}).get("ood", {}).get("seed_offset", 999))

    oracle.setdefault("rl", {})
    oracle["rl"]["epochs"] = max(1, int(round(float(oracle["rl"].get("epochs", 1)) * args.epochs_mult)))
    oracle["rl"]["steps_per_epoch"] = max(1, int(round(float(oracle["rl"].get("steps_per_epoch", 1)) * args.steps_mult)))

    meta = oracle.setdefault("meta", {})
    meta["oracle_of"] = args.primary
    meta["oracle_generated"] = True
    meta["oracle_note"] = "Generated by scripts/make_oracle_config.py; env/eval use primary eval.ood distribution."

    save_yaml(oracle, args.out)
    print(f"Wrote oracle config to {args.out}")


if __name__ == "__main__":
    main()
